name: Android CI

on:
  push:
    branches-ignore:
      - 'main'
      - 'release'
  pull_request:
    branches:
      - 'release'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Create Google Service Account File
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Create upload key
        run: |
          # Base64でエンコードされたキーストアファイルをシークレットからでコードする
          echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
          # シークレットからキーストア関連情報を読み取りlocal.propertiesに書き込む
          echo "keystore.file=keystore.jks" >> local.properties
          echo "keystore.password=${{ secrets.STORE_PASSWORD }}" >> local.properties
          echo "keystore.alias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "keystore.keypwd=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Unit Test & Coverage
        run: ./gradlew testDebugUnitTest jacocoTestReport
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReportDebug

  ui-test:
    # releaseブランチに対するプルリクエストが作成されたときに実行する
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0.3.1
        id: auth
        with:
          create_credentials_file: true
          workload_identity_pool: ${{ secrets.WORKLOAD_IDENTITY_POOL }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: gcloud login
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file }}"

      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build Debug
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app-debug.apk
          ./gradlew assembleAndroidTest
          mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk app-debug-androidTest.apk

      - name: UI Test on Firebase TestLab
        run: |
          gcloud firebase test android run --type instrumentation --app app-debug.apk --test app-debug-androidTest.apk \
          --device model=Pixel6,version=33,locale=en,orientation=portrait \
          --device model=Pixel6,version=31,locale=en,orientation=portrait \
          --device model=Pixel5,version=30,locale=en,orientation=portrait \
          --device model=a10,version=29,locale=en,orientation=portrait \
          --device model=Nexus5,version=21,locale=en,orientation=portrait

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Create Google Service Account File
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Create upload key
        run: |
          # Base64でエンコードされたキーストアファイルをシークレットからでコードする
          echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
          # シークレットからキーストア関連情報を読み取りlocal.propertiesに書き込む
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Build Release
        run: ./gradlew assembleRelease

      - name: Upload to Play Console
        run: |
          echo ${{ secrets.PLAY_CONSOLE_KEY }} | base64 --decode > key.json
          ./gradlew publishReleaseBundle --track=production --key-file=key.json --service-account-email=${{ secrets.SERVICE_ACCOUNT_EMAIL }}
